[package]
name = "sweat_claim"
version = "1.0.0"
authors = ["Sweat Economy"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = { workspace = true }
uint = { version = "0.9.3", default-features = false }
